### ISSUE TITLE
Avoid Secure Boot in latest BIOS versions

### ISSUE THREAD

**Issue by roy-tc** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#10]
Props for this extensive documentation! This saved me many hours.

As noted in the Readme:
```
Note: After update to 1502 - unable to boot from non-Windows HDD, rolled back to 1401. (09-May-2020)
```

I managed to get around this by setting `OS Type` to `Other`. This disables Secure Boot and lets you boot form non-Windows HDDs.

Cheers!

**Comment by vovinacci** [comment]
Thanks for the issue! Tried that, but it didn't work on `0.5.8`. However, I think that this may be fixed in `0.5.9` with `BootProtect` set to `Bootstrap` instead of `None`. Will check it over the weekend.

**Comment by roy-tc** [comment]
Good point; I forgot to mention that this was indeed working on `0.5.9` specifically for me.

Thanks!

**Comment by vovinacci** [comment]
Updated to 1502 and it works now. It's all in `0.5.9` and `BootProtect` setting.
