### ISSUE TITLE
OpenCore has been updated to 0.8, is this repository still maintained?

### ISSUE THREAD

**Issue by Umenezumi** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#108]
as the title suggests...

**Comment by vovinacci** [comment]
@Umenezumi JFYI, I've regained back access to the hardware - https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/releases/tag/0.8.1
