### ISSUE TITLE
Opencore does not detect my mac partition

### ISSUE THREAD

**Issue by piyuyi** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#125]
Hi, with your last version 0.8.5 it doesn't detect my mac system partition (apfs) on opencore boot, only the efi partition.
Also not in a few previous ones I have tried.
Do you know why it could be?

Thanks for sharing your efi folder :-)

**Comment by lvxianchao** [comment]
@piyuyi try this:

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/22412818/200175350-9e3b0fe4-d1ef-4b30-bee1-a64eae601258.png">

if you OCC version is higher than the installed system version, try this:

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/22412818/200175560-8fed446c-44f0-4093-b5ee-78057cc18439.png">

**Comment by piyuyi** [comment]
> @piyuyi try this:
> 
> <img alt="image" width="1364" src="https://user-images.githubusercontent.com/22412818/200175350-9e3b0fe4-d1ef-4b30-bee1-a64eae601258.png">
> 
> if you OCC version is higher than the installed system version, try this:
> 
> <img alt="image" width="1316" src="https://user-images.githubusercontent.com/22412818/200175560-8fed446c-44f0-4093-b5ee-78057cc18439.png">

It works! You are the boss 😎.

Thank you!

**Comment by vovinacci** [comment]
@piyuyi @lvxianchao Something to learn for me as well, many thanks!
Shall we close the issue as it is resolved?

**Comment by piyuyi** [comment]
Yes!
Thank you!
