### ISSUE TITLE
Error displayed during startup. Do you know how to solve it?

### ISSUE THREAD

**Issue by JasmineYong** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#144]
M11H motherboard of the same model, 8700k processor

![屏幕截图 2023-08-19 225423](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/assets/45485611/964333d4-b522-4fb6-8e09-f13a21e0154e)

**Comment by JasmineYong** [comment]
![IMG_0908](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/assets/45485611/ec9e26ac-58f2-48dc-99c7-2746dc849562)

**Comment by vovinacci** [comment]
@JasmineYong It seems that you didn't change `{{MACADDRESS}}` (and most likely other fields) to your specific values.

See, https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#download-efi-folder-archive-from-repository-releases-page
