### ISSUE TITLE
Error creating EFI folder

### ISSUE THREAD

**Issue by piyuyi** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#27]
Hello. In your latest version, 0.6.1, the config.plist appears completely empty when I open it.

can you check and fix it, please?
Thank you.

**Comment by vovinacci** [comment]
Hi, thanks for the report. I've generated whole `EFI` folder again and it is all just fine.
Do you have an output from the script?

**Comment by piyuyi** [comment]
I send you your generated EFI folder with the command (bash -c "$(curl -fsSL raw.githubusercontent.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/master/create-efi.sh)

I think the config.plist is empty.....


[EFI.zip](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/files/5214990/EFI.zip)

**Comment by piyuyi** [comment]
Can you send me from here directly your EFI folder, to compare?

**Comment by piyuyi** [comment]
I send you my bash process.

[Bash process.txt](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/files/5215045/Bash.process.txt)

**Comment by vovinacci** [comment]
@piyuyi Thanks for all the details you've sent. I took your `EFI.zip` and ran `bash -c "$(curl -fsSL raw.githubusercontent.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/master/create-efi.sh)`. That gave me identical `config.plist`.

Here are the details for your convenience.
```
$ tar -ztvf ./EFI.zip |grep config.plist
-rw-r--r--  0 501    20      24570 13 Sep 22:29 EFI/OC/config.plist
$ bash -c "$(curl -fsSL raw.githubusercontent.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/master/create-efi.sh)" > /dev/null 2>&1
$ ls -l EFI/OC/config.plist
-rw-r--r-- 1 vovinacci staff 24570 Sep 14 10:01 EFI/OC/config.plist
$
```

To me, this means that everything works as expected.
I've replaced all the serial number with ones, that are used locally and rebooted. Everything works just fine.
```
$ sudo diskutil mount /dev/disk0s1
Volume EFI on /dev/disk0s1 mounted
$ ls -lah /Volumes/EFI/EFI/
total 2.5K
drwxrwxrwx 1 vovinacci  512 Sep  9 06:47 .
drwxrwxrwx 1 vovinacci  512 Sep 14 10:16 ..
drwxrwxrwx 1 vovinacci  512 Sep  9 06:47 BOOT
drwxrwxrwx 1 vovinacci 1.0K Sep  9 06:47 OC
$
```

**Comment by vovinacci** [comment]
P.S. I've missed to install it for real when writing comment. Amended comment above a bit.

**Comment by piyuyi** [comment]
Ok, but the problem is that when I try to open the config.plist to insert the serial numbers, it appears completely empty, all sections. I open it with the last version of opencore configurator (2.12.1.0).

Any solution?

**Comment by piyuyi** [comment]
I have finally discovered the problem. Your config.plist is not compatible with version 0.6.1, so it is not read by the latest version of opencore configurator.

**Comment by vovinacci** [comment]
@piyuyi I am confused.

Step by step.
- `config.plist` in this repo is based on https://github.com/acidanthera/OpenCorePkg/blob/0.6.1/Docs/Sample.plist. I've added `plist` linter check to ensure that it's not corrupted or anything - looking good. You can run `plutil /path/to/config.ist` to ensure this as well.
- I use the very same `config.plist` myself and it works just fine.
- I do not use any OpenCore configuration tools as per my previous experience it's quite often broken. The very same stated [here](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#starting-point). To me this is the most reasonable guide, so I'm following it.
- Prior merging any version upgrade to `master`, `config.plist` is always checked against [Sanity Checker](https://opencore.slowgeek.com) (this link is mentioned in the README)

Taking into account stated above, I don't think that `config.plist` in this repo is not compatible with OpenCore 0.6.1. For some reason, unknown to me, it cannot be opened by some tool - sorry, cannot help with this as I'm not the author that tool.

Apart of this, assuming that you have the same hardware as stated in README, did you try to boot with the resulting `EFI`?

**Comment by piyuyi** [comment]
Fisrt of all, thank you for your time.
I do not start the system with your efi, and I am exhausted. That is why I have finally decided to try it with the beta 6 of big sur, and avoid future problems again. 
Have you tried to start big sur with the maximus hero xi?

**Comment by vovinacci** [comment]
No worries at all.
I'm on Catalina and cannot really play around with Big Sur upgrade as this is my workhorse - won't be able to work if I brick it. Sorry for that.

**Comment by piyuyi** [comment]
I understand you.
I hope that with the final version of big sur, you change your mind.

Thank you and I close the thread.
