### ISSUE TITLE
longer boot times with OC 0.6.1 than OC 0.6.0

### ISSUE THREAD

**Issue by joncas** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#33]
Hello
I wonder whether you have also experienced longer boot times with OC 0.6.1 than OC 0.6.0 ?
Looking at the system log, the time from BOOTTIME to desktop increased from 35 seconds to 50 seconds.
It's not a big deal because everything else seems to work normally, except that with OC 0.6.1 the "Little Snitch" firewall initially cannot connect and gives an error message, so maybe that is the cause. I suppose it could have to do with the "force" addition for IONetworkingFamily.kext (whatever that does).
In any case, many thanks for having taen the time to update your install to 061 so quickly !

**Comment by vovinacci** [comment]
Hi @joncas,

  To be honest, boot time stayed more or less the same as I didn't really notice the difference. Just rebooted to measure, it's around 40 seconds now.

  I don't use Little Snitch, relying on default firewall, sorry cannot be really in help with it.

  Did quick googling around `IONetworkingFamily.kext` and found deprecation notice from Apple on it - https://developer.apple.com/support/kernel-extensions/. It's still part of the system (could be found at `/S/L/E/IONetworkingFamily.kext`), looking through logs locally, don't see any mentions of it (according the doc above - should trigger notification)

  And yes, you're very much welcome! :)
