### ISSUE TITLE
unable to boot

### ISSUE THREAD

**Issue by eeonee** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#43]
Hi,

I am unable to boot into the installer, I just get the apple logo stuck..

What am I doing wrong?

**Comment by vovinacci** [comment]
Hi,

To be honest, I have no idea as there's too little information available to troubleshoot.

A quick checklist to help you to start with troubleshooting:

- Do you have the very same hardware configuration as I do?
- Did you change [board serial](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/blob/0.6.3/OC/config.plist#L894), [MAC address](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/blob/0.6.3/OC/config.plist#L898), [system serial](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/blob/0.6.3/OC/config.plist#L904) and [system UUID](https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/blob/0.6.3/OC/config.plist#L906)? What it is and how to generate these values is described [here](https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html) and [here](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#generate-a-new-serial)

In general, mostly everything I know, comes from [Dortania Guides](https://dortania.github.io/OpenCore-Install-Guide/).

**Comment by eeonee** [comment]
Hi, Do you have discord so we can talk?

Thanks

**Comment by vovinacci** [comment]
Unfortunately, I don't have a Discord, sorry for that.

I've quickly checked GTX 1070 and it seems that I have bad news for you - https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/nvidia-gpu.html#pascal-series-gtx-10xx.

Re internal GPU - I have explicitly set to use external GPU in BIOS. Generally, you may want to try add `-wegnoegpu` to the boot flags as per https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html to ensure that you're on iGPU.

I've added possibility to install `DEBUG` version of OpenCore - just run `OC_PKG_VARIANT=DEBUG` prior running `create-efi.sh` and that would make it. So, at least you will have logs.

It would be hard for me to support you more as our hardware configuration differs and all can do is to provide you with links to the documentation (Dortania) and Google for the symptoms and solutions.

**Comment by eeonee** [comment]
Is there any other way we can communicate am eager to get this working, I got my Dell XPS working.

Cant get this for the hell of it.

Please

**Comment by hcwilhelm** [comment]
Hi, 

I am getting the exact same issue as @eeonee and get stuck on the Apple logo, after a while the system reboots. My hardware is nearly the same as in the hardware list I just have a Vega56 instead of the RX580. I am going to try the debug version next and will provide my findings here. 

In the config.plist I couldn't find the `{{MACADDRESS}}` placeholder so I was following the dortania guide and put the mac address into `Platforminfo -> Generic -> Rom`

**Comment by eeonee** [comment]
> Hi,
> 
> I am getting the exact same issue as @eeonee and get stuck on the Apple logo, after a while the system reboots. My hardware is nearly the same as in the hardware list I just have a Vega56 instead of the RX580. I am going to try the debug version next and will provide my findings here.
> 
> In the config.plist I couldn't find the `{{MACADDRESS}}` placeholder so I was following the dortania guide and put the mac address into `Platforminfo -> Generic -> Rom`

Hi you can find the Mac address if you use a plist editor, its marked with {{MACADDRESS}}.

**Comment by hcwilhelm** [comment]
Yes my bad I found it here, 

https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/blob/e63f9244ea4dca04794bd8c1d5c47becc618c433/OC/config.plist#L898

**Comment by eeonee** [comment]
> Yes my bad I found it here,
> 
> https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/blob/e63f9244ea4dca04794bd8c1d5c47becc618c433/OC/config.plist#L898

Also if you edit the config.plist add to the bootargs -v for verbose this will tell you where its hanging.

**Comment by hcwilhelm** [comment]
So I booted in debug mode and in the logs I find 

```
12:098 00:035 AAPL: [EB|`LD:LKC] SB -> (System\Library\PrelinkedKernels\immutablekernel)
12:136 00:038 AAPL: [EB|`LD:LKC] BPDK -> (System\Library\PrelinkedKernels\immutablekernel.development)
12:176 00:040 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: System\\Library\\PrelinkedKernels\\immutablekernel.development, DP: 0
12:219 00:042 AAPL: [EB|`LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\immutablekernel.development)
12:257 00:038 AAPL: [EB|`LD:LKC] BPDK,!R -> (System\Library\PrelinkedKernels\immutablekernel)
12:296 00:038 AAPL: [EB|`LD:LF] FIO: 0, DIR: 1, P: System\\Library\\PrelinkedKernels\\immutablekernel, DP: 0
12:351 00:055 OC: Plist Kexts\USBMap.kext\Contents\Info.plist is missing for injected kext USBMap.kext (USB port mapping)
```

So the info.plist for the USBMap.kext is missing currently I am not sure where I find that file, but I try to investigate.

**Comment by vovinacci** [comment]
@hcwilhelm Normally it should be at `EFI/OC/Kexts/USBMap.kext/Contents/Info.plist` in `EFI` volume. Just quickly tested - it's there. There've been similar issue https://github.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/issues/16, when Coreutils were not present and Kext was placed to the wrong location. Could you please check?

**Comment by hcwilhelm** [comment]
@vovinacci I checked it and i found `EFI/OC/Kexts/USBMap.kext/USBMap.kext/Contents/Info.plist` so the kext is somehow double nested. I removed the nesting and it works like a charm. So what did is 

Move `EFI/OC/Kexts/USBMap.kext/USBMap.kext -> EFI/OC/Kexts/USBMap.kext`

**Comment by vovinacci** [comment]
@hcwilhelm Thanks for the update! I'm very much curious about the setup you have (packages, path, etc.), so that I can address this issue.

**Comment by hcwilhelm** [comment]
@vovinacci sure so what I did is 

- I did follow your guide and used `bash -c "$(curl -fsSL raw.githubusercontent.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/master/create-efi.sh)"` to setup the EFI folder. 

- Configure `{{SERIAL}}, {{BOARDSERIAL}} , {{SMUUID}} and {{MACADDRESS}}` 

- And as I final step I moved `EFI/OC/Kexts/USBMap.kext/USBMap.kext -> EFI/OC/Kexts/USBMap.kext` to get rid of the nesting of a kext inside a kext

and that's it. 

<img width="280" alt="Bildschirmfoto 2020-12-01 um 12 24 58" src="https://user-images.githubusercontent.com/604578/100734624-3f1cd380-33d0-11eb-94c2-768f161151db.png">

**Comment by hcwilhelm** [comment]
So now my Bluetooth is working now but my front header USB ports stopped working. I guess I have to create my own USBMap.kext to adapt it to my setup. This 15 port limit is annoying ;)

**Comment by vovinacci** [comment]
@hcwilhelm Thanks again. Do you have Coreutils installed on the machine where you did run `bash -c "$(curl -fsSL raw.githubusercontent.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/master/create-efi.sh)`? What the bash version? I'm really curious. Thanks in advance!

**Comment by eeonee** [comment]
@hcwilhelm Can you post your efi and config.plist please.

@vovinacci how do you run the create-efi.sh if you can't boot into the Mac OS?

Thanks

**Comment by hcwilhelm** [comment]
- Yes I have coreutils `coreutils: stable 8.32 (bottled), HEAD`
- Bash is `GNU bash, Version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)`

Anything else that you need to know?

**Comment by hcwilhelm** [comment]
@eeonee Yes, I have discord.

**Comment by eeonee** [comment]
> @eeonee Yes, I have discord. Anyways I can share my EFI folder

please can you share it and send me your discord

Thanks

**Comment by hcwilhelm** [comment]
@eeonee My discord name is `hcwilhelm#0568`

**Comment by eeonee** [comment]
> hcwilhelm#0568

req sent

**Comment by vovinacci** [comment]
@eeonee I run it from my old Mac mini or wife's Macbook. Generally, I also have USB stick with last working EFI and macOS installer to be able to boot.

**Comment by vovinacci** [comment]
@hcwilhelm Thanks for the update! These are exactly the versions I have as well. As a matter of one more courtesy, can you share your `PATH` variable value?

**Comment by hcwilhelm** [comment]
@vovinacci sure

```
echo $PATH
/Users/hcwilhelm/zalando-cli/bin:/usr/local/opt/python@3.7/bin:/Users/hcwilhelm/.jenv/shims:/Users/hcwilhelm/.jenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
```

**Comment by vovinacci** [comment]
@hcwilhelm PATH looks familiar. :) The only thing that differs is that you don't have `/usr/local/opt/coreutils/libexec/gnubin` in PATH like I do. I'll create PR quickly to add it to the install script and would ask you to test if you have time.

**Comment by hcwilhelm** [comment]
@vovinacci Sure no problem

**Comment by vovinacci** [comment]
@hcwilhelm You may want to run install script as `bash -c "$(curl -fsSL raw.githubusercontent.com/vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO/add-coreutils-path/create-efi.sh)"`. Seems like I've introduced regression when added `DEBUG` version support. Need to write tests to track issues like this.

**Comment by hcwilhelm** [comment]
@vovinacci Anyways I tested it and it's fine now. No nexted USBMap.kext anymore 👍

**Comment by vovinacci** [comment]
@eeonee Can this issue be closed? I'm anyway cannot help you efficiently with different hardware setup. To help you to troubleshoot OC DEBUG version support been added. But I would be curious to know what was the root cause when it is all fixed.
