### ISSUE TITLE
plist

### ISSUE THREAD

**Issue by svan71** [vovinacci/OpenCore-ASUS-ROG-MAXIMUS-XI-HERO#64]
opening config.plist I get a padding error. The plist appears to be default from opencore.  Without a working config.plist included, minus serials and rom info this really isn't very helpful.

**Comment by vovinacci** [comment]
Hi, thanks for the report.

- Could you please elaborate on how do you open plist file?
- Is there anything specific that you're missing there?

I'm using resulting plist myself and didn't have any issues so far.
